=== mmurauer/CrAc/Code/CrAc/build/classes/inloc/inloc_schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:inloc="http://purl.org/net/inloc/"
	targetNamespace="http://purl.org/net/inloc/"
	xmlns:xml="http://www.w3.org/XML/1998/namespace"
	elementFormDefault="qualified">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"
		schemaLocation="http://www.w3.org/2001/xml.xsd"/>

	<xs:annotation>
		<xs:documentation>
			Version 2012-06-09 initial release
		</xs:documentation>
		<xs:documentation>
			Version 2012-07-06
			Several changes/clarification after first early feedback on the interim report:
			- LOCdefinition could not contain any other main LOC elements (other LOCdefinition, LOCrelation, LOCProperty)
			- Several types (elements) have been externalized to allow their reuse (propertyType, RelationshipTypeID
			- and clarify the modelling with common reuse types LOCtypeMultilingualToken and LOCtypeMultilingualString
			- add the prefix "LOCtype" to all complextype defined in the inloc schema
			- full URLs for the relationshipTypeID
			- change sequence to choice for the LOCstructure so that child elements could be in any order.
		</xs:documentation>
		<xs:documentation>
			Version 2012-10-31
			added two new elements to the LOCtypeRelationshipTypeID:
			* definesGenericLevel
			* isDefinedGenericLevelOf
			LOCtypeRelationshipTypeID removed, replaced with an annotation in 2013-04-24 in order to simplify the schema

		</xs:documentation>
		<xs:documentation>
			Version 2012-11-12
			added the primaryStructure element to the LOCDefinition type
		</xs:documentation>
		<xs:documentation>
			Version 2012-11-14
			allow any other attribute to furtherInformation element with validation process only if a schema is provided (lax)
		</xs:documentation>
		<xs:documentation>
			Version 2013-04-24
			tidying up without any significant change - annotation moved here from 2012-10-31 and corrected:
			Where the _type_ attribute is "LOCrel", the *scheme* _id_ must be one of:
			* "http://purl.org/net/inloc/closeMatch"
			* "http://www.w3.org/2004/02/skos/core#closeMatch"
			* "http://purl.org/net/inloc/exactMatch"
			* "http://www.w3.org/2004/02/skos/core#exactMatch"
			* "http://purl.org/net/inloc/hasDefinedLevel"
			* "http://purl.org/net/inloc/hasExample"
			* "http://purl.org/net/inloc/hasLOCpart"
			* "http://purl.org/net/inloc/hasNecessaryPart"
			* "http://purl.org/net/inloc/hasOptionalPart"
			* "http://purl.org/net/inloc/hasPreRequisite"
			* "http://purl.org/net/inloc/isDefinedLevelOf"
			* "http://purl.org/net/inloc/isExampleOf"
			* "http://purl.org/net/inloc/isLOCpartOf"
			* "http://purl.org/net/inloc/isNecessaryPartOf"
			* "http://purl.org/net/inloc/isOptionalPartOf"
			* "http://purl.org/net/inloc/isPreRequisiteOf"
			* "http://purl.org/net/inloc/isReplacedBy"
			* "http://purl.org/dc/terms/isReplacedBy"
			* "http://purl.org/net/inloc/related"
			* "http://www.w3.org/2004/02/skos/core#related"
			* "http://purl.org/dc/terms/relation"
			* "http://purl.org/net/inloc/replaces"
			* "http://purl.org/dc/terms/replaces"
			Where the _type_ attribute is "by", the *scheme* _id_ must be one of:
			* "http://purl.org/net/inloc/contributor"
			* "http://purl.org/dc/terms/contributor"
			* "http://purl.org/net/inloc/creator"
			* "http://purl.org/dc/terms/creator"
			* "http://purl.org/net/inloc/publisher"
			* "http://purl.org/dc/terms/publisher"
			* "http://purl.org/net/inloc/rightsHolder"
			* "http://purl.org/dc/terms/rightsHolder"
		</xs:documentation>
	</xs:annotation>

	<!-- Multilingual TYPES -->
	
	<xs:complexType name="LOCtypeMultilingualToken">
		<xs:simpleContent>
			<xs:extension base="xs:token">
				<xs:attribute ref="xml:lang"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="LOCtypeMultilingualString">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute ref="xml:lang"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="LOCtypeMultilingualStringAnyAttribute">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute ref="xml:lang"/>
				<xs:anyAttribute processContents="lax"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
		
	<!-- TYPES for LOC Structure and LOC Defintion -->

	<xs:complexType name="LOCtypeLOC" abstract="true">
    	<xs:sequence>
    		<xs:element name="extraID" type="xs:anyURI" minOccurs="0" maxOccurs="unbounded"/>
    		<xs:element name="title" type="inloc:LOCtypeMultilingualToken" minOccurs="0" maxOccurs="unbounded"/>
    		<xs:element name="abbr" type="inloc:LOCtypeMultilingualToken" minOccurs="0" maxOccurs="unbounded"/>
    		<xs:element name="description" type="inloc:LOCtypeMultilingualString" minOccurs="0" maxOccurs="unbounded"/>
    		<xs:element name="furtherInformation" type="inloc:LOCtypeMultilingualStringAnyAttribute" minOccurs="0" maxOccurs="unbounded"/>
    		<xs:element name="rights" type="inloc:LOCtypeMultilingualString" minOccurs="0" maxOccurs="unbounded"/>
    		<xs:element name="created" type="xs:dateTime" minOccurs="0"/>
    		<xs:element name="modified" type="xs:dateTime" minOccurs="0" maxOccurs="unbounded"/>
    		<xs:element name="issued" type="xs:dateTime" minOccurs="0"/>
    		<xs:element name="validityStart" type="xs:dateTime" minOccurs="0"/>
    		<xs:element name="validityEnd" type="xs:dateTime" minOccurs="0"/>
    		<xs:element name="version" type="xs:token" minOccurs="0"/>
    	</xs:sequence>
		<xs:attribute name="id"  type="xs:anyURI" use="required"/>
		<xs:attribute ref="xml:lang"/>
	</xs:complexType>

	<xs:complexType name="LOCdefinition">
		<xs:complexContent>
			<xs:extension base="inloc:LOCtypeLOC">
			<xs:sequence>
				<xs:element name="primaryStructure" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="LOCstructure">
    	<xs:complexContent>
    		<xs:extension base="inloc:LOCtypeLOC">
    			<xs:sequence>
    				<xs:element name="combinationRules" type="inloc:LOCtypeMultilingualString" minOccurs="0" maxOccurs="unbounded"/>
    				<xs:choice minOccurs="0" maxOccurs="unbounded">
    					<xs:element name="LOCstructure" type="inloc:LOCstructure"/>
    					<xs:element name="LOCdefinition" type="inloc:LOCdefinition"/>
    					<xs:element name="LOCassociation" type="inloc:LOCassociation"/>
    				</xs:choice>
    			</xs:sequence>
    		</xs:extension>
    	</xs:complexContent>
    </xs:complexType>
	
    <!-- TYPES for LOC Association -->

	<xs:simpleType name="LOCtypeAssociationType">
			<xs:restriction base="xs:anyURI">
				<xs:enumeration value="http://purl.org/net/inloc/LOCrel"/>
				<xs:enumeration value="http://purl.org/net/inloc/by"/>
				<xs:enumeration value="http://purl.org/net/inloc/category"/>
				<xs:enumeration value="http://purl.org/net/inloc/credit"/>
				<xs:enumeration value="http://purl.org/net/inloc/level"/>
				<xs:enumeration value="http://purl.org/net/inloc/topic"/>
			</xs:restriction>
		</xs:simpleType>
	
	<xs:complexType name="Subject">
		<xs:sequence>
			<xs:element name="label" type="inloc:LOCtypeMultilingualToken" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id"  type="xs:anyURI" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="SchemeObject">
		<xs:sequence>
			<xs:element name="label" type="inloc:LOCtypeMultilingualToken" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id"  type="xs:anyURI"/>
	</xs:complexType>

	<xs:complexType name="LOCassociation">
		<xs:sequence>
			<xs:element name="subject" type="inloc:Subject" maxOccurs="1" minOccurs="1"/>
			<xs:element name="scheme" type="inloc:SchemeObject" maxOccurs="1" minOccurs="1"/>
			<xs:element name="object" type="inloc:SchemeObject" maxOccurs="1" minOccurs="1"/>
			<xs:element name="number" type="xs:decimal" maxOccurs="1" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id"  type="xs:anyURI"/>
		<xs:attribute name="type"  type="inloc:LOCtypeAssociationType" use="required"/>
	</xs:complexType>

    <!-- root ELEMENT -->
	<xs:element name="LOCstructure" type="inloc:LOCstructure"></xs:element>
	
</xs:schema>

=== mmurauer/CrAc/Code/CrAc/build/classes/inloc/competencies/crac_languages.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This is a demo collection of some competencies for prototyping purposes
	v 1.0 -->

<!-- first, the LOC structure and its direct properties -->
<LOCstructure xmlns="http://purl.org/net/inloc/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://purl.org/net/inloc/ http://purl.org/net/inloc/inloc_schema.xsd"
	xml:lang="en" id="http://inloc.crac.at/language_competencies/v1">
	<!-- the last two attributes above put clearly as they are significant -->
	<title>Languages</title>
	<abbr>CRAC Language Competencies</abbr>
	<rights></rights>
	<created>2015-06-07T00:00:00</created>
	<version>1.0</version>

	<LOCassociation type="http://purl.org/net/inloc/by">
		<subject id="http://inloc.crac.at/interests/v1" />
		<scheme id="http://purl.org/net/inloc/creator">
			<label xml:lang="en">Author</label>
		</scheme>
		<object id="">
			<label>Florian Jungwirth, Michaela Murauer</label>
		</object>
	</LOCassociation>

	<!-- English -->
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/language_competencies/v1" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/competencies/v1/Languages/E" />
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/competencies/v1/Languages/E">
		<title>English</title>
	</LOCdefinition>
	
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/competencies/v1/Languages/E" />
		<scheme id="http://purl.org/net/inloc/hasDefinedLevel" />
		<object id="http://inloc.crac.at/competencies/v1/Languages/E/1" />
		<number>1</number>
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/competencies/v1/Languages/E/1">
		<description>Basic Knowledge</description>
	</LOCdefinition>
	
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/competencies/v1/Languages/E" />
		<scheme id="http://purl.org/net/inloc/hasDefinedLevel" />
		<object id="http://inloc.crac.at/competencies/v1/Languages/E/2" />
		<number>2</number>
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/competencies/v1/Languages/E/2">
		<description>Advanced Knowledge</description>
	</LOCdefinition>
	
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/competencies/v1/Languages/E" />
		<scheme id="http://purl.org/net/inloc/hasDefinedLevel" />
		<object id="http://inloc.crac.at/competencies/v1/Languages/E/3" />
		<number>3</number>
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/competencies/v1/Languages/E/3">
		<description>Native Speaker</description>
	</LOCdefinition>
	<!-- French -->
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/language_competencies/v1" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/competencies/v1/Languages/F" />
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/competencies/v1/Languages/F">
		<title>French</title>
	</LOCdefinition>
	
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/competencies/v1/Languages/F" />
		<scheme id="http://purl.org/net/inloc/hasDefinedLevel" />
		<object id="http://inloc.crac.at/competencies/v1/Languages/F/1" />
		<number>1</number>
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/competencies/v1/Languages/F/1">
		<description>Basic Knowledge</description>
	</LOCdefinition>
	
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/competencies/v1/Languages/F" />
		<scheme id="http://purl.org/net/inloc/hasDefinedLevel" />
		<object id="http://inloc.crac.at/competencies/v1/Languages/F/2" />
		<number>2</number>
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/competencies/v1/Languages/F/2">
		<description>Advanced Knowledge</description>
	</LOCdefinition>
	
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/competencies/v1/Languages/F" />
		<scheme id="http://purl.org/net/inloc/hasDefinedLevel" />
		<object id="http://inloc.crac.at/competencies/v1/Languages/F/3" />
		<number>3</number>
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/competencies/v1/Languages/F/3">
		<description>Native Speaker</description>
	</LOCdefinition>
	
	<!-- German -->
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/language_competencies/v1" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/competencies/v1/Languages/G" />
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/competencies/v1/Languages/G">
		<title>German</title>
	</LOCdefinition>
	
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/competencies/v1/Languages/G" />
		<scheme id="http://purl.org/net/inloc/hasDefinedLevel" />
		<object id="http://inloc.crac.at/competencies/v1/Languages/G/1" />
		<number>1</number>
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/competencies/v1/Languages/G/1">
		<description>Basic Knowledge</description>
	</LOCdefinition>
	
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/competencies/v1/Languages/G" />
		<scheme id="http://purl.org/net/inloc/hasDefinedLevel" />
		<object id="http://inloc.crac.at/competencies/v1/Languages/G/2" />
		<number>2</number>
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/competencies/v1/Languages/G/2">
		<description>Advanced Knowledge</description>
	</LOCdefinition>
	
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/competencies/v1/Languages/G" />
		<scheme id="http://purl.org/net/inloc/hasDefinedLevel" />
		<object id="http://inloc.crac.at/competencies/v1/Languages/G/3" />
		<number>3</number>
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/competencies/v1/Languages/G/3">
		<description>Native Speaker</description>
	</LOCdefinition>
</LOCstructure>

=== mmurauer/CrAc/Code/CrAc/build/classes/inloc/competencies/crac_drivinglicencesxml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This is a demo collection of some competencies for prototyping purposes
	v 1.0 -->

<!-- first, the LOC structure and its direct properties -->
<LOCstructure xmlns="http://purl.org/net/inloc/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://purl.org/net/inloc/ http://purl.org/net/inloc/inloc_schema.xsd"
	xml:lang="en" id="http://inloc.crac.at/drivinglicences_competencies/v1">
	<!-- the last two attributes above put clearly as they are significant -->
	<title>Driving Licences</title>
	<abbr>CRAC Driving Licences Competencies</abbr>
	<rights></rights>
	<created>2015-06-07T00:00:00</created>
	<version>1.0</version>

	<LOCassociation type="http://purl.org/net/inloc/by">
		<subject id="http://inloc.crac.at/interests/v1" />
		<scheme id="http://purl.org/net/inloc/creator">
			<label xml:lang="en">Author</label>
		</scheme>
		<object id="">
			<label>Florian Jungwirth, Michaela Murauer</label>
		</object>
	</LOCassociation>
	
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/drivinglicences_competencies/v1" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/competencies/v1/DrivingLicences/A" />
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/competencies/v1/DrivingLicences/A">
		<title>A</title>
	</LOCdefinition>
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/drivinglicences_competencies/v1" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/competencies/v1/DrivingLicences/B" />
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/competencies/v1/DrivingLicences/B">
		<title>B</title>
	</LOCdefinition>
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/drivinglicences_competencies/v1" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/competencies/v1/DrivingLicences/C" />
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/competencies/v1/DrivingLicences/C">
		<title>C</title>
	</LOCdefinition>
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/drivinglicences_competencies/v1" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/competencies/v1/DrivingLicences/D" />
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/competencies/v1/DrivingLicences/D">
		<title>D</title>
	</LOCdefinition>
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/drivinglicences_competencies/v1" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/competencies/v1/DrivingLicences/F" />
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/competencies/v1/DrivingLicences/F">
		<title>F</title>
	</LOCdefinition>
</LOCstructure>

=== mmurauer/CrAc/Code/CrAc/src/inloc/interests/crac_interests_v1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This is a dummy collection of some interests for prototyping purposes
	v 1.0 -->

<!-- first, the LOC structure and its direct properties -->
<LOCstructure xmlns="http://purl.org/net/inloc/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://purl.org/net/inloc/ http://purl.org/net/inloc/inloc_schema.xsd"
	xml:lang="en" id="http://inloc.crac.at/interests/v1">
	<!-- the last two attributes above put clearly as they are significant -->
	<title>CoopeRative ACtivities Interests Framework</title>
	<abbr>CRAC Interests</abbr>
	<rights></rights>
	<created>2015-04-07T00:00:00</created>
	<version>1.0</version>

	<LOCassociation type="http://purl.org/net/inloc/by">
		<subject id="http://inloc.crac.at/interests/v1" />
		<scheme id="http://purl.org/net/inloc/creator">
			<label xml:lang="en">Author</label>
		</scheme>
		<object id="">
			<label>Florian Jungwirth, Michaela Murauer</label>
		</object>
	</LOCassociation>

	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/interests/v1" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/interests/v1/Indoor" />
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/interests/v1/Indoor">
		<title>Indoor</title>
	</LOCdefinition>

	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/interests/v1" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/interests/v1/Outdoor" />
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/interests/v1/Outdoor">
		<title>Outdoor</title>
	</LOCdefinition>
	
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/interests/v1" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/interests/v1/Collection" />
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/interests/v1/Collection">
		<title>Collection</title>
	</LOCdefinition>
	
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/interests/v1/Indoor" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/interests/v1/Indoor/1" />
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/interests/v1/Indoor/1">
		<title>Drawing</title>
	</LOCdefinition>
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/interests/v1/Indoor" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/interests/v1/Indoor/2" />
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/interests/v1/Indoor/2">
		<title>Writing</title>
	</LOCdefinition>
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/interests/v1/Indoor" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/interests/v1/Indoor/3" />
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/interests/v1/Indoor/3">
		<title>Dancing</title>
	</LOCdefinition>
	
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/interests/v1/Outdoor" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/interests/v1/Outdoor/1" />
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/interests/v1/Outdoor/1">
		<title>Biking</title>
	</LOCdefinition>
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/interests/v1/Outdoor" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/interests/v1/Outdoor/2" />
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/interests/v1/Outdoor/2">
		<title>Running</title>
	</LOCdefinition>
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/interests/v1/Outdoor" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/interests/v1/Outdoor/3" />
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/interests/v1/Outdoor/3">
		<title>Yoga</title>
	</LOCdefinition>
	
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/interests/v1/Indoor" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/interests/v1/Outdoor/3" />
	</LOCassociation>
	
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/interests/v1/Collection" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/interests/v1/Collection/1" />
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/interests/v1/Collection/1">
		<title>Cards</title>
	</LOCdefinition>
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/interests/v1/Collection" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/interests/v1/Collection/2" />
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/interests/v1/Collection/2">
		<title>Cars</title>
	</LOCdefinition>
	<LOCassociation type="http://purl.org/net/inloc/LOCrel">
		<subject id="http://inloc.crac.at/interests/v1/Collection" />
		<scheme id="http://purl.org/net/inloc/hasLOCpart" />
		<object id="http://inloc.crac.at/interests/v1/Collection/3" />
	</LOCassociation>
	<LOCdefinition id="http://inloc.crac.at/interests/v1/Collection/3">
		<title>Coins</title>
	</LOCdefinition>
</LOCstructure>
